In [1]:
import numpy as np, random, operator, pandas as pd, matplotlib.pyplot as plt


cities = [0,1,2,3,4,5,6,7,8,9,10]

matr=np.zeros([len(cities),len(cities)])

for i in range(len(cities)):
    for j in range(len(cities)):
        matr[i][j]=matr[j][i]=np.random.randint(50,100)
        if (i==j):
            matr[i][j]=0
            
print(matr)

class Population():
    def __init__(self, bag, matr):
        self.bag = bag
        self.parents = []
        self.score = 0
        self.best = None
        self.matr = matr

def init_population(cities, matr, n_population):
    return Population(
        np.asarray([np.random.permutation(cities) for _ in range(n_population)]), 
        matr
    )

pop = init_population(cities, matr, 5)

def fitness(self, gen):
    return sum(
        [
            self.matr[gen[i], gen[i + 1]]
            for i in range(len(gen) - 1)
        ]
    )

Population.fitness = fitness

def evaluate(self):
    distances = np.asarray(
        [self.fitness(gen) for gen in self.bag]
    )
    self.score = np.min(distances)
    self.best = self.bag[distances.tolist().index(self.score)]
    self.parents.append(self.best)
    if False in (distances[0] == distances):
        distances = np.max(distances) - distances
    return distances / np.sum(distances)
    
Population.evaluate = evaluate


def select(self, k=4):
    fit = self.evaluate()
    while len(self.parents) < k:
        idx = np.random.randint(0, len(fit))
        if fit[idx] > np.random.rand():
            self.parents.append(self.bag[idx])
    self.parents = np.asarray(self.parents)

Population.select = select

pop.select()
pop.parents

def swap(gen):
    a, b = np.random.choice(len(gen), 2)
    gen[a], gen[b] = (
        gen[b],
        gen[a],
    )
    return gen

def crossover(self, p_cross=0.1):
    children = []
    count, size = self.parents.shape
    for _ in range(len(self.bag)):
        if np.random.rand() > p_cross:
            children.append(
                list(self.parents[np.random.randint(count, size=1)[0]])
            )
        else:
            parent1, parent2 = self.parents[
                np.random.randint(count, size=2), :
            ]
            idx = np.random.choice(range(size), size=2, replace=False)
            start, end = min(idx), max(idx)
            child = [None] * size
            for i in range(start, end + 1, 1):
                child[i] = parent1[i]
            pointer = 0
            for i in range(size):
                if child[i] is None:
                    while parent2[pointer] in child:
                        pointer += 1
                    child[i] = parent2[pointer]
            children.append(child)
    return children

Population.crossover = crossover

def mutate(self, p_cross=0.1, p_mut=0.1):
    next_bag = []
    children = self.crossover(p_cross)
    for child in children:
        if np.random.rand() < p_mut:
            next_bag.append(swap(child))
        else:
            next_bag.append(child)
    return next_bag
    
Population.mutate = mutate

pop.mutate()


def genetic_algorithm(
    cities,
    matr,
    n_population=600,
    n_iter=100,
    selectivity=0.2,
    p_cross=0.5,
    p_mut=0.1,
    print_interval=100,
    return_history=False,
    verbose=False,
):
    pop = init_population(cities, matr, n_population)
    best = pop.best
    score = float("inf")
    history = []
    for i in range(n_iter):
        pop.select(n_population * selectivity)
        history.append(pop.score)
        if verbose:
            print(f"Поколение {i}: Расстояние: {pop.score}")
        elif i % print_interval == 0:
            print(f"Поколение {i}: Расстояние: {pop.score}")
        if pop.score < score:
            best = pop.best
            score = pop.score
        children = pop.mutate(p_cross, p_mut)
        pop = Population(children, pop.matr)
    if return_history:
        return best, history
    print('\n')
    print("Лучший короткий путь:")
    return best

genetic_algorithm(cities,matr,verbose=True)

[[ 0. 82. 97. 92. 97. 63. 97. 62. 64. 64. 56.]
 [82.  0. 97. 93. 61. 78. 70. 65. 96. 83. 77.]
 [97. 97.  0. 60. 66. 86. 99. 92. 71. 98. 91.]
 [92. 93. 60.  0. 99. 92. 88. 81. 68. 74. 53.]
 [97. 61. 66. 99.  0. 50. 88. 93. 60. 63. 69.]
 [63. 78. 86. 92. 50.  0. 92. 95. 75. 95. 81.]
 [97. 70. 99. 88. 88. 92.  0. 99. 75. 98. 52.]
 [62. 65. 92. 81. 93. 95. 99.  0. 71. 84. 78.]
 [64. 96. 71. 68. 60. 75. 75. 71.  0. 84. 72.]
 [64. 83. 98. 74. 63. 95. 98. 84. 84.  0. 96.]
 [56. 77. 91. 53. 69. 81. 52. 78. 72. 96.  0.]]
Поколение 0: Расстояние: 668.0
Поколение 1: Расстояние: 667.0
Поколение 2: Расстояние: 667.0
Поколение 3: Расстояние: 652.0
Поколение 4: Расстояние: 625.0
Поколение 5: Расстояние: 632.0
Поколение 6: Расстояние: 632.0
Поколение 7: Расстояние: 632.0
Поколение 8: Расстояние: 632.0
Поколение 9: Расстояние: 632.0
Поколение 10: Расстояние: 632.0
Поколение 11: Расстояние: 632.0
Поколение 12: Расстояние: 632.0
Поколение 13: Расстояние: 615.0
Поколение 14: Расстояние: 615.0
Поколение 15

[9, 0, 7, 1, 6, 10, 3, 2, 8, 4, 5]